### ISSUE TITLE
Support managed instances

### ISSUE THREAD

**Issue by hoegertn** [disneystreaming/ssm-helpers#19]
When you have hybrid instances in SSM, which are named `mi-xxxx` the command `ssm-session`fails with:

```
ERROR Could not retrieve tags for instance mi-xyz
InvalidInstanceID.Malformed: Invalid id: "mi-xyz"
	status code: 400, request id: 6ebb7606-96be-????-????-28db42edeca6
```

**Comment by sendqueery** [comment]
The issue you're seeing is that when we check for instance readiness, we also take that time to grab the EC2 tags for that instance, since they aren't shared between SSM and EC2. Managed instances aren't EC2 instances, and this never popped up in my testing because, well, I didn't see any of them. My bad! 😅

I'll need to find some managed instances to test on before I can verify that this works properly, but I think I've got at least the readiness check fixed. :)

**Comment by rothgar** [comment]
We should be able to skip tag lookups if the instance starts with `mi` but there's probably a better way to tell

**Comment by sendqueery** [comment]
> We should be able to skip tag lookups if the instance starts with `mi` but there's probably a better way to tell

D'oh, you're right. We can check ResourceType! Updated.

**Comment by sendqueery** [comment]
@hoegertn this is fixed by the linked PR, but will not be effective until a release of both the library and binaries is tagged, just FYI

**Comment by hoegertn** [comment]
Thanks

**Comment by viesti** [comment]
Hmm, I think I still see something similar here. I created one managed instance and can start a session into it with `aws ssm start-session --target mi-xxxx`, but when running `ssm session` I get this error:

```
0% ssm session
panic: runtime error: index out of range [0] with length 0

goroutine 19 [running]:
github.com/disneystreaming/ssm-helpers/ssm.CheckInstanceReadiness(0xc0000996c0, 0x1e6e600, 0xc0000a0108, 0xc000512030, 0x1, 0x1, 0x1, 0xc000081ac0)
	/home/runner/work/ssm-helpers/ssm-helpers/ssm/helpers.go:208 +0x728
github.com/disneystreaming/ssm-helpers/cmd.startSessionCommand.func1(0xc0000a9064, 0xc0000994a0, 0xc0000994c0, 0xc0000a00c8, 0xc0000a9060, 0xc0000a9050, 0xc0000996c0, 0xc000081ac0)
	/home/runner/work/ssm-helpers/ssm-helpers/cmd/session.go:138 +0x206
created by github.com/disneystreaming/ssm-helpers/cmd.startSessionCommand
	/home/runner/work/ssm-helpers/ssm-helpers/cmd/session.go:114 +0xa2a
```

I think the problem lies somewhere in
```
instanceInfo, err := ec2helpers.GetEC2InstanceInfo(ec2Client, ec2Instances)
```
which I guess uses EC2 API to get instance information, while for managed instances, the API to use is [DescribeInstanceInformation](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_DescribeInstanceInformation.html).
